Add ssh action
User can ssh into a container, or even into an image.
docker-tool will first try /bin/bash, then try /bin/sh.

diff --git a/docker-tool b/docker-tool
--- a/docker-tool
+++ b/docker-tool
@@ -1,5 +1,4 @@
 #!/bin/bash
-set -o errexit
 
 # default ENVs
 DOCKER_SOCK='unix:///var/run/docker.sock'
@@ -20,20 +19,20 @@ print_usage() {
 	sudo ./docker-tool <action> [args...]
 
 	Actions:
-		clean-img                  | Clean dangling images
-		clean-vol                  | (DANGEROUS!!!) Clean dangling volumes, who are not referenced by any containers
-		img <name>                 | Grep image by given <name>
-		net <container-id/name>    | Show network info (mode, veth pair, ...) of container
-		ns-net <container-id/name> | Enter the net namespace of container, with all host's tools available. Use "exit" to exit
-		pid <container-id/name>    | Get the pid of container
-		run                        | == "docker run -it"
-		ssh <container-id/name>    | Enter the bash/sh of container
+		clean-img                        | Clean dangling images
+		clean-vol                        | (DANGEROUS!!!) Clean dangling volumes, who are not referenced by any containers
+		img <name>                       | Grep image by given <name>
+		net <container-id/name>          | Show network info (mode, veth pair, ...) of a container
+		ns-net <container-id/name>       | Enter the net namespace of a container, with all host's tools available. Use "exit" to exit
+		pid <container-id/name>          | Get the pid of a container
+		run ...                          | == docker run -it ...
+		ssh <container-id/name or image> | Enter the bash/sh of a container or image
 
 	EOF
 }
 
 # -----------------
-# Utils
+# Utils - common
 # -----------------
 
 # echo with 256 color
@@ -71,9 +70,10 @@ ensure_command_exists() {
 }
 
 # Prompt a string to ask user y/n
-# Usage: ask_user [what you want to ask]
 # It returns exit code to indicate user's answer. 
-# In Linux, exit code 0 -> ok, 1 -> error
+# Exit code 0 -> ok, 1 -> error
+# Usage:
+#   if ask_user [what you want to ask] ; then ... ; fi
 ask_user() {
 	local answer
 	echo ""
@@ -86,6 +86,45 @@ ask_user() {
 			return 1
 			;;
 	esac
+	return 1
+}
+
+# -----------------
+# Utils - Docker
+# -----------------
+
+# Whether this is a Docker image name, already pulled
+# Exit code 0 -> ok, 1 -> error
+# Usage:
+#   if is_image <name> ; then ... ; fi
+is_image() {
+	local keyword=$1
+	# If keyword doesn't have a colon, which means no tag specified, add "latest" tag for it
+	if [ $(echo $keyword | cut -s -d ':' -f 1 | wc -l) -eq 0 ] ; then
+		keyword=${keyword}:latest
+	fi
+	if [ $($DOCKER images -q $keyword | wc -l) -gt 0 ] ; then
+		return 0
+	fi
+	return 1
+}
+
+# Whether this is a Docker container ID/name
+# Exit code 0 -> ok, 1 -> error
+# Usage:
+#   if is_container <name> ; then ... ; fi
+is_container() {
+	local keyword=$1
+	# Try to match with container ID
+	if [ $($DOCKER ps -q -f "id=$keyword" | wc -l) -gt 0 ] ; then
+		return 0
+	fi
+	# Try to match with container fullname
+	for c_name in $($DOCKER ps --format "{{.Names}}") ; do
+		if [ $c_name = $keyword ] ; then
+			return 0
+		fi
+	done
 	return 1
 }
 
@@ -175,21 +214,46 @@ action_ns_net() {
 
 action_ssh() {
 	ensure_count_args 1 "$@"
-
 	local name=$1
-	# We don't use 'which' to detect command in containers because 'which' is not installed in some images.
-	# But in most cases, 'ls' is installed. Nor, probably there's no other commands availble.
-	if $DOCKER exec -it $name ls /bin/bash > /dev/null 2>&1 ; then
-		echo_color 148 "Enter ${name}, using /bin/bash"
-		$DOCKER exec -it $name /bin/bash
-		return $?
-	elif $DOCKER exec -it $name ls > /dev/null 2>&1 ; then
-		echo_color 148 "Enter ${name}, using /bin/sh"
-		$DOCKER exec -it $name /bin/sh
-		return $?
+
+	if is_container $name ; then
+		# We don't use 'which' to detect command in containers because 'which' is not installed in some images.
+		# But in most cases, 'ls' is installed. Nor, probably there's no other commands availble.
+		if $DOCKER exec -it $name ls /bin/bash > /dev/null 2>&1 ; then
+			echo_color 148 "Enter container '${name}', using /bin/bash"
+			$DOCKER exec -it $name /bin/bash
+			return $?
+		elif $DOCKER exec -it $name ls > /dev/null 2>&1 ; then
+			echo_color 148 "Enter container '${name}', using /bin/sh"
+			$DOCKER exec -it $name /bin/sh
+			return $?
+		fi
+		echo_err "cannot find '/bin/bash' or '/bin/sh' in container: $name"
+		return 1
 	fi
-	echo_err "cannot find '/bin/bash' or '/bin/sh' in container:$name"
-	return 1
+
+	if is_image $name ; then
+		echo_color 148 "Enter image '${name}'"
+
+		echo_color 64 "- Try to use /bin/bash"
+		$($DOCKER run -it --rm --entrypoint=/bin/bash $name)
+		local exit_code=$?
+		echo $exit_code
+		if [ ! $exit_code -eq 125 ] && [ ! $exit_code -eq 127 ] ; then  # exit code 125: exec failed, 127: no such command
+			return $exit_code
+		fi
+
+		echo_color 64 "- Try to use /bin/sh"
+		$DOCKER run -it --rm --entrypoint=/bin/sh $name
+		if [ ! $? -eq 125 ] && [ ! $? -eq 127 ] ; then
+			return $?
+		fi
+
+		echo_err "cannot find '/bin/bash' or '/bin/sh' in image: $name"
+		return 1
+	fi
+
+	echo_err "'$name' is not a container id/fullname, nor an image name"
 }
 
 action_run() {
